version: '3.8'
services:
  backend:
    image: backend:latest
    container_name: astrosync_api_server
    build:
      context: ./
      dockerfile: backend.dockerfile
    environment:
      GS_ADDR: ${GS_ADDR?Variable not set}
      PROJECT_NAME: ${PROJECT_NAME?Variable not set}
      DOMAIN: ${DOMAIN?Variable not set}
      MONGO_DB_PORT: ${MONGO_DB_PORT?Variable not set}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME?Variable not set}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD?Variable not set}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS?Variable not set}
      AUTH_URL: ${AUTH_URL?Variable not set}
      REALM: ${REALM?Variable not set}
      CLIENT_ID: ${CLIENT_ID?Variable not set}
      API_PORT: ${API_PORT?Variable not set}
    ports:
      - 8083:8080
    depends_on:
      - "mongodb"
    volumes:
      - .:/api_server
    networks:
      - webserver_default

  mongodb:
    image: mongo:4.4.6
    container_name: astrosync_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME?Variable not set}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD?Variable not set}
    ports:
      - ${MONGO_DB_PORT?Variable not set}:${MONGO_DB_PORT?Variable not set}
    # volumes:
    #   - ./db:/data/db
    command: mongod --quiet --logpath /dev/null
    networks:
      - webserver_default

networks:
  webserver_default:
    external: true